# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.parser]
    wrapStandAloneImageWithinParagraph = false

  [goldmark.renderer]
    unsafe = true

  [goldmark.extensions]
  [goldmark.extensions.passthrough]
    enable = true
    [goldmark.extensions.passthrough.delimiters]
      block = [['\[', '\]'], ['$$', '$$']]
      inline = [['\(', '\)'], ['$', '$']]

[highlight]
  noClasses = false
  lineNos = true
  lineNumbersInTable = true
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  style = "github"
  lineNosStart = 1
  lineNoStart = 1

[tableOfContents]
  startLevel = 2
  endLevel = 4
