# baseURL 会根据环境自动设置
# 本地开发: http://localhost:1313/blog/
# 生产环境: https://benchuat.github.io/blog/ (GitHub Actions 会自动设置)
baseURL = "http://benchuat.github.io/"
title = "BenChuat's Blog"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
pluralizeListTitles = false
theme = "blowfish"



[languages]
[languages."zh-cn"]
  languageCode = "zh-cn"
  languageName = "简体中文"
  weight = 1
  title = "BenChuat的记录本"
  contentDir = "content/zh-cn"
  [languages."zh-cn".params]
    displayName = "简体中文"
    isoCode = "zh-CN"
    dateFormat = "2006年01月02日"
    mainSections = ["posts"]
    # 这里就不贴 author 了，反正你已经配了

[languages.en]
  languageCode = "en"
  languageName = "EN"
  weight = 2
  title = "BenChuat’s Blog"
  contentDir = "content/en"
  [languages.en.params]
    displayName = "EN"
    isoCode = "en"
    dateFormat = "2 January 2006"
    mainSections = ["posts"]
